apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-audit
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: cluster-audit
          image: REPLACE_WITH_REGISTRY/cluster-audit:latest
          env:
            - name: OUT_DIR
              value: /tmp/output
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      restartPolicy: Never
      volumes:
        - name: tmp
          emptyDir: {}
